// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flbsjkwexphjsyclsoac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsYnNqa3dleHBoanN5Y2xzb2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTIwNDIsImV4cCI6MjA2MzU4ODA0Mn0.32MtyR5xRIMdWgeskQPGb4Z6lypYvXhh0eQ8TJe2amA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);